// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: measure.proto

package cn.wfy.netty.vo;

public final class MeasureProto {
  private MeasureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface measureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:measure)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string remark = 3;</code>
     * @return The remark.
     */
    String getRemark();
    /**
     * <code>string remark = 3;</code>
     * @return The bytes for remark.
     */
    com.google.protobuf.ByteString
        getRemarkBytes();

    /**
     * <code>string salespersonId = 4;</code>
     * @return The salespersonId.
     */
    String getSalespersonId();
    /**
     * <code>string salespersonId = 4;</code>
     * @return The bytes for salespersonId.
     */
    com.google.protobuf.ByteString
        getSalespersonIdBytes();

    /**
     * <code>string templateId = 5;</code>
     * @return The templateId.
     */
    String getTemplateId();
    /**
     * <code>string templateId = 5;</code>
     * @return The bytes for templateId.
     */
    com.google.protobuf.ByteString
        getTemplateIdBytes();

    /**
     * <code>string orgStructNodeId = 6;</code>
     * @return The orgStructNodeId.
     */
    String getOrgStructNodeId();
    /**
     * <code>string orgStructNodeId = 6;</code>
     * @return The bytes for orgStructNodeId.
     */
    com.google.protobuf.ByteString
        getOrgStructNodeIdBytes();

    /**
     * <code>string companyId = 7;</code>
     * @return The companyId.
     */
    String getCompanyId();
    /**
     * <code>string companyId = 7;</code>
     * @return The bytes for companyId.
     */
    com.google.protobuf.ByteString
        getCompanyIdBytes();
  }
  /**
   * Protobuf type {@code measure}
   */
  public static final class measure extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:measure)
      measureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use measure.newBuilder() to construct.
    private measure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private measure() {
      id_ = "";
      name_ = "";
      remark_ = "";
      salespersonId_ = "";
      templateId_ = "";
      orgStructNodeId_ = "";
      companyId_ = "";
    }


    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private measure(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              remark_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              salespersonId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              templateId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              orgStructNodeId_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              companyId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MeasureProto.internal_static_measure_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MeasureProto.internal_static_measure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              measure.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMARK_FIELD_NUMBER = 3;
    private volatile Object remark_;
    /**
     * <code>string remark = 3;</code>
     * @return The remark.
     */
    @Override
    public String getRemark() {
      Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      }
    }
    /**
     * <code>string remark = 3;</code>
     * @return The bytes for remark.
     */
    @Override
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALESPERSONID_FIELD_NUMBER = 4;
    private volatile Object salespersonId_;
    /**
     * <code>string salespersonId = 4;</code>
     * @return The salespersonId.
     */
    @Override
    public String getSalespersonId() {
      Object ref = salespersonId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        salespersonId_ = s;
        return s;
      }
    }
    /**
     * <code>string salespersonId = 4;</code>
     * @return The bytes for salespersonId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSalespersonIdBytes() {
      Object ref = salespersonId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        salespersonId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPLATEID_FIELD_NUMBER = 5;
    private volatile Object templateId_;
    /**
     * <code>string templateId = 5;</code>
     * @return The templateId.
     */
    @Override
    public String getTemplateId() {
      Object ref = templateId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        templateId_ = s;
        return s;
      }
    }
    /**
     * <code>string templateId = 5;</code>
     * @return The bytes for templateId.
     */
    @Override
    public com.google.protobuf.ByteString
        getTemplateIdBytes() {
      Object ref = templateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        templateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORGSTRUCTNODEID_FIELD_NUMBER = 6;
    private volatile Object orgStructNodeId_;
    /**
     * <code>string orgStructNodeId = 6;</code>
     * @return The orgStructNodeId.
     */
    @Override
    public String getOrgStructNodeId() {
      Object ref = orgStructNodeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orgStructNodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string orgStructNodeId = 6;</code>
     * @return The bytes for orgStructNodeId.
     */
    @Override
    public com.google.protobuf.ByteString
        getOrgStructNodeIdBytes() {
      Object ref = orgStructNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orgStructNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYID_FIELD_NUMBER = 7;
    private volatile Object companyId_;
    /**
     * <code>string companyId = 7;</code>
     * @return The companyId.
     */
    @Override
    public String getCompanyId() {
      Object ref = companyId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        companyId_ = s;
        return s;
      }
    }
    /**
     * <code>string companyId = 7;</code>
     * @return The bytes for companyId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCompanyIdBytes() {
      Object ref = companyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        companyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getRemarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, remark_);
      }
      if (!getSalespersonIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, salespersonId_);
      }
      if (!getTemplateIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, templateId_);
      }
      if (!getOrgStructNodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, orgStructNodeId_);
      }
      if (!getCompanyIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, companyId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getRemarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, remark_);
      }
      if (!getSalespersonIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, salespersonId_);
      }
      if (!getTemplateIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, templateId_);
      }
      if (!getOrgStructNodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, orgStructNodeId_);
      }
      if (!getCompanyIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, companyId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof measure)) {
        return super.equals(obj);
      }
      measure other = (measure) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getRemark()
          .equals(other.getRemark())) return false;
      if (!getSalespersonId()
          .equals(other.getSalespersonId())) return false;
      if (!getTemplateId()
          .equals(other.getTemplateId())) return false;
      if (!getOrgStructNodeId()
          .equals(other.getOrgStructNodeId())) return false;
      if (!getCompanyId()
          .equals(other.getCompanyId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
      hash = (37 * hash) + SALESPERSONID_FIELD_NUMBER;
      hash = (53 * hash) + getSalespersonId().hashCode();
      hash = (37 * hash) + TEMPLATEID_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateId().hashCode();
      hash = (37 * hash) + ORGSTRUCTNODEID_FIELD_NUMBER;
      hash = (53 * hash) + getOrgStructNodeId().hashCode();
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static measure parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static measure parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static measure parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static measure parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static measure parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static measure parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static measure parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static measure parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static measure parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static measure parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static measure parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static measure parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(measure prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code measure}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:measure)
        measureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MeasureProto.internal_static_measure_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MeasureProto.internal_static_measure_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                measure.class, Builder.class);
      }

      // Construct using cn.wfy.netty.vo.MeasureProto.measure.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        remark_ = "";

        salespersonId_ = "";

        templateId_ = "";

        orgStructNodeId_ = "";

        companyId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MeasureProto.internal_static_measure_descriptor;
      }

      @Override
      public measure getDefaultInstanceForType() {
        return measure.getDefaultInstance();
      }

      @Override
      public measure build() {
        measure result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public measure buildPartial() {
        measure result = new measure(this);
        result.id_ = id_;
        result.name_ = name_;
        result.remark_ = remark_;
        result.salespersonId_ = salespersonId_;
        result.templateId_ = templateId_;
        result.orgStructNodeId_ = orgStructNodeId_;
        result.companyId_ = companyId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof measure) {
          return mergeFrom((measure)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(measure other) {
        if (other == measure.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getRemark().isEmpty()) {
          remark_ = other.remark_;
          onChanged();
        }
        if (!other.getSalespersonId().isEmpty()) {
          salespersonId_ = other.salespersonId_;
          onChanged();
        }
        if (!other.getTemplateId().isEmpty()) {
          templateId_ = other.templateId_;
          onChanged();
        }
        if (!other.getOrgStructNodeId().isEmpty()) {
          orgStructNodeId_ = other.orgStructNodeId_;
          onChanged();
        }
        if (!other.getCompanyId().isEmpty()) {
          companyId_ = other.companyId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        measure parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (measure) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object remark_ = "";
      /**
       * <code>string remark = 3;</code>
       * @return The remark.
       */
      public String getRemark() {
        Object ref = remark_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       * @return The bytes for remark.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes() {
        Object ref = remark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string remark = 3;</code>
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      /**
       * <code>string remark = 3;</code>
       * @param value The bytes for remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remark_ = value;
        onChanged();
        return this;
      }

      private Object salespersonId_ = "";
      /**
       * <code>string salespersonId = 4;</code>
       * @return The salespersonId.
       */
      public String getSalespersonId() {
        Object ref = salespersonId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          salespersonId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string salespersonId = 4;</code>
       * @return The bytes for salespersonId.
       */
      public com.google.protobuf.ByteString
          getSalespersonIdBytes() {
        Object ref = salespersonId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          salespersonId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string salespersonId = 4;</code>
       * @param value The salespersonId to set.
       * @return This builder for chaining.
       */
      public Builder setSalespersonId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        salespersonId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string salespersonId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalespersonId() {
        
        salespersonId_ = getDefaultInstance().getSalespersonId();
        onChanged();
        return this;
      }
      /**
       * <code>string salespersonId = 4;</code>
       * @param value The bytes for salespersonId to set.
       * @return This builder for chaining.
       */
      public Builder setSalespersonIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        salespersonId_ = value;
        onChanged();
        return this;
      }

      private Object templateId_ = "";
      /**
       * <code>string templateId = 5;</code>
       * @return The templateId.
       */
      public String getTemplateId() {
        Object ref = templateId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          templateId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string templateId = 5;</code>
       * @return The bytes for templateId.
       */
      public com.google.protobuf.ByteString
          getTemplateIdBytes() {
        Object ref = templateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          templateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string templateId = 5;</code>
       * @param value The templateId to set.
       * @return This builder for chaining.
       */
      public Builder setTemplateId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string templateId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemplateId() {
        
        templateId_ = getDefaultInstance().getTemplateId();
        onChanged();
        return this;
      }
      /**
       * <code>string templateId = 5;</code>
       * @param value The bytes for templateId to set.
       * @return This builder for chaining.
       */
      public Builder setTemplateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateId_ = value;
        onChanged();
        return this;
      }

      private Object orgStructNodeId_ = "";
      /**
       * <code>string orgStructNodeId = 6;</code>
       * @return The orgStructNodeId.
       */
      public String getOrgStructNodeId() {
        Object ref = orgStructNodeId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          orgStructNodeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string orgStructNodeId = 6;</code>
       * @return The bytes for orgStructNodeId.
       */
      public com.google.protobuf.ByteString
          getOrgStructNodeIdBytes() {
        Object ref = orgStructNodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orgStructNodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orgStructNodeId = 6;</code>
       * @param value The orgStructNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setOrgStructNodeId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orgStructNodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orgStructNodeId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrgStructNodeId() {
        
        orgStructNodeId_ = getDefaultInstance().getOrgStructNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>string orgStructNodeId = 6;</code>
       * @param value The bytes for orgStructNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setOrgStructNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orgStructNodeId_ = value;
        onChanged();
        return this;
      }

      private Object companyId_ = "";
      /**
       * <code>string companyId = 7;</code>
       * @return The companyId.
       */
      public String getCompanyId() {
        Object ref = companyId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          companyId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string companyId = 7;</code>
       * @return The bytes for companyId.
       */
      public com.google.protobuf.ByteString
          getCompanyIdBytes() {
        Object ref = companyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          companyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string companyId = 7;</code>
       * @param value The companyId to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string companyId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompanyId() {
        
        companyId_ = getDefaultInstance().getCompanyId();
        onChanged();
        return this;
      }
      /**
       * <code>string companyId = 7;</code>
       * @param value The bytes for companyId to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        companyId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:measure)
    }

    // @@protoc_insertion_point(class_scope:measure)
    private static final measure DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new measure();
    }

    public static measure getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<measure>
        PARSER = new com.google.protobuf.AbstractParser<measure>() {
      @Override
      public measure parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new measure(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<measure> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<measure> getParserForType() {
      return PARSER;
    }

    @Override
    public measure getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_measure_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_measure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmeasure.proto\"\212\001\n\007measure\022\n\n\002id\030\001 \001(\t\022" +
      "\014\n\004name\030\002 \001(\t\022\016\n\006remark\030\003 \001(\t\022\025\n\rsalespe" +
      "rsonId\030\004 \001(\t\022\022\n\ntemplateId\030\005 \001(\t\022\027\n\017orgS" +
      "tructNodeId\030\006 \001(\t\022\021\n\tcompanyId\030\007 \001(\tB\'\n\027" +
      "cn.wfy.thread.runner.voB\014MeasureProtob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_measure_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_measure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_measure_descriptor,
        new String[] { "Id", "Name", "Remark", "SalespersonId", "TemplateId", "OrgStructNodeId", "CompanyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
